// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations run DDL statements, which require a direct (non-pooled)
    // connection to Postgres. The app itself connects via DATABASE_URL
    // (pooled, through Supabase's connection pooler) using a driver adapter —
    // see src/lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
